CHANGELOG.md, lib/backup-k8up.libjsonnet
=> Only import Crossplane lib if required

CHANGELOG.md, class/defaults.yml
=> Update wrestic default version to v0.2.0

component/monitoring.jsonnet
=> add prometheus_name label to servicemonitor

CHANGELOG.md, class/defaults.yml, component/app.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc
=> Implement disable switch

.gitignore, CHANGELOG.md, class/backup-k8up.yml, class/defaults.yml, docs/modules/ROOT/pages/how-tos/upgrade.adoc, docs/modules/ROOT/pages/references/parameters.adoc, docs/modules/ROOT/partials/nav.adoc, lib/backup-k8up.libjsonnet
* Deploy CRD's
* Refactor to expose all Helm Values
Closes #17
Closes #4
=> update to work with K8up 1.0+

class/defaults.yml
=> Update K8up to v1.0.5

class/defaults.yml
=> Update k8up to v1.1.0, wrestic to v0.3.1

class/defaults.yml
=> Fix wrong indentation for the image helmValues for the k8up image

.github/workflows/release.yaml
=> Fix release action to display "x commits to master since this release"

docs/modules/ROOT/pages/how-tos/upgrade-v1-v2.adoc
=> Remove stray :w in component docs

class/defaults.yml
=> Update wrestic version to v0.3.2

.sync.yml
=> Add modulesync configuration

docs/modules/ROOT/pages/how-tos/upgrade-v1-v2.adoc
=> Fix external links

docs/modules/ROOT/pages/how-tos/upgrade-v2-v3.adoc
=> Fix not all legacy crd are mentioned in upgrade howto

class/defaults.yml, tests/golden/v2/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/clusterrolebinding.yaml, tests/golden/v2/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/deployment.yaml, tests/golden/v2/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/operator-clusterrole.yaml, tests/golden/v2/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/service.yaml, tests/golden/v2/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/serviceaccount.yaml
Update to https://github.com/k8up-io/k8up/releases/tag/k8up-3.0.1
* Regession: Adds RBAC permission for events.
=> Update K8up chart to v3.0.1

class/defaults.yml, tests/golden/v2/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/clusterrolebinding.yaml, tests/golden/v2/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/deployment.yaml, tests/golden/v2/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/operator-clusterrole.yaml, tests/golden/v2/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/service.yaml, tests/golden/v2/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/serviceaccount.yaml, tests/golden/v2/backup-k8up/backup-k8up/02_k8up_crds.yaml
=> Bump Chart k8up to v3.0.2

class/defaults.yml, tests/golden/v1/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/deployment.yaml, tests/golden/v1/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/rbac.yaml, tests/golden/v1/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/service.yaml, tests/golden/v2/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/clusterrolebinding.yaml, tests/golden/v2/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/deployment.yaml, tests/golden/v2/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/operator-clusterrole.yaml, tests/golden/v2/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/service.yaml, tests/golden/v2/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/user-clusterrole.yaml
=> Bump k8up version

class/defaults.yml, tests/golden/defaults/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/cleanup-hook.yaml, tests/golden/defaults/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/clusterrolebinding.yaml, tests/golden/defaults/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/deployment.yaml, tests/golden/defaults/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/executor-clusterrole.yaml, tests/golden/defaults/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/operator-clusterrole.yaml, tests/golden/defaults/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/service.yaml, tests/golden/defaults/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/serviceaccount.yaml, tests/golden/defaults/backup-k8up/backup-k8up/02_k8up_crds.yaml
=> Update K8up to v2.7.1 and Helm chart to 4.3.0

class/defaults.yml, docs/modules/ROOT/pages/references/parameters.adoc, tests/golden/defaults/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/deployment.yaml
=> Add option to skip backups for PVCs that aren't explicitly annotated

.cruft.json, class/backup-k8up.yml, class/defaults.yml, component/app.jsonnet
Template version: main (f12cbb4)
changelog.
=> Update from template

lib/backup-k8up.libjsonnet
=> Support configuring TLS Options

lib/backup-k8up.libjsonnet
=> Fix definition of TLS Options

lib/backup-k8up.libjsonnet
=> Change Secret to ConfigMap
