projectsyn/component-backup-k8up

CHANGELOG.md
class/defaults.yml

This reverts commit 87401e0513095613793800f65ed37835864c93c6.
We observed backups getting stuck with wrestic v0.2.0, so we're globally
reverting the version bump.

Revert "Update wrestic default version to v0.2.0"

---

CHANGELOG.md
class/defaults.yml
component/monitoring.jsonnet
docs/modules/ROOT/pages/references/parameters.adoc

Directly access variables of other components create implicit dependencies. Instead each component must define their own parameters with or without defaults. It is then the responsibility of the config hierarchy to glue components together.
This PR removes the use of `parameters.synsights.prometheus.name` and replaces it with `prometheus_name` owned by this component.

Introduce parameter for configuring the Prometheus name

---

CHANGELOG.md
class/defaults.yml

Docker Hub has introduced a rate limit for docker pulls,
so solve this for all, this switches the registry to quay.io.

Switch docker registry from docker.io to quay.io

---

CHANGELOG.md
class/defaults.yml
component/monitoring.jsonnet
docs/modules/ROOT/pages/references/parameters.adoc

Moving the alert definitions to `parameters.backup_k8up.monitoring_alerts` allows users of the component to selectively adjust/replace/extend the set of alerts which are deployed for K8up.

Move alert definitions to parameters

---

CHANGELOG.md
class/defaults.yml
docs/modules/ROOT/pages/references/parameters.adoc

With the old alert configuration, alerts would only be raised after ~48h, leading to a high likelihood that more than one scheduled backup was missed (assuming daily backups).

Reduce time a K8up job needs to be queued to raise an alert

---

CHANGELOG.md
class/defaults.yml
docs/modules/ROOT/pages/references/parameters.adoc

By default, alert for backups which take longer than 30 minutes

Add alert to warn about slow backups

---

CHANGELOG.md

Selecting v1.0.0 over v0.1.0 because this component is already used in production all over the place.

Prepare release for v1.0.0

---

CHANGELOG.md
class/backup-k8up.yml
class/defaults.yml
docs/modules/ROOT/pages/references/parameters.adoc
postprocess/filters.yml

Fixes #22.
Also cleans up the component implementation to
* use the helm dependency type to fetch the K8up helm chart
* move postprocessing filter configuration into the hierarchy

Fix CRD version handling and clean up component implementation

---

.github/changelog-configuration.json

I forgot to add this file in #24  :facepalm: 

Fix missing changelog config

---

component/app.jsonnet

* This PR teaches ArgoCD to ignore certain CRD properties when they are applied with the legacy CRD spec for OpenShift.
Without it, ArgoCD fails to properly sync the component manifests.
Closes https://github.com/vshn/k8up/issues/445

Ignore CRD properties in ArgoCD sync

---

class/defaults.yml
component/monitoring.jsonnet
docs/modules/ROOT/pages/references/parameters.adoc

This PR upgrades the `k8up` helm chart to `v1.1.0` and the underlying `k8up` to `v1.2.0`.
It takes the new alert rules from the updated helm chart and replaces the `keepjobs` field with the new `failedJobsHistoryLimit` and `successfulJobsHistoryLimit` fields.
⚠️ https://github.com/vshn/k8up/pull/471 should be merged first to have proper, working links.

Upgrade k8up, new alert rules, remove deprecated keepJobs

---

class/defaults.yml
component/app.jsonnet
docs/modules/ROOT/pages/how-tos/upgrade-v2-v3.adoc
docs/modules/ROOT/pages/references/parameters.adoc
docs/modules/ROOT/partials/nav.adoc
tests/defaults.yml

* Deprecates `enabled` parameter. Recent Commodore versions can do it natively, but there are cases where this parameter is still used for legacy reasons.

Deprecate 'enabled' parameter

---

docs/modules/ROOT/pages/how-tos/upgrade-v2-v3.adoc

* Adds step after upgrade to forEach `kubectl delete crd`. This should ensure that users cannot create K8up v1 resources anymore after upgrade (e.g. via outdated forgotten pipeline).

Document step to cleanup CRDs of v1 after upgrade

---

component/main.jsonnet
docs/modules/ROOT/pages/references/parameters.adoc

For OpenShift 4, the namespace needs to be labeled with `openshift.io/cluster-monitoring=true` for the `PrometheusRule` and `ServiceMonitor` objects to be picked up by OpenShift cluster-monitoring.

Set correct monitoring label on namespace for OCP4

---

docs/modules/ROOT/pages/references/parameters.adoc
lib/backup-k8up.libjsonnet

We add logic to omit field `promURL` from K8up resources (schedules and checks) if the user sets `parameters.backup_k8up.prometheus_push_gateway` to `null`.
Additionally, we document how the component handles a `null` value for the parameter.
Fixes #12

Omit `promURL` in K8up resources if `prometheus_push_gateway` is `null`

---

class/backup-k8up.yml

We want to use `backup_k8up:charts:k8up:version` for specifying the Helm chart dependency output directory with the new Helm chart configuration structure.

Fix Helm chart dependency directory

---

class/backup-k8up.yml
class/defaults.yml

We restructure the K8up container image specification to populate `backup_k8up:images:k8up` from the lookup table containing the default image versions for K8up v1.x and v2.x instead of populating v2 of the lookup table from `backup_k8up:images:k8up`.
While breaking the Commodore component best practices, this brings the container image specification in line with the Helm chart specification and restructures the class enough to avoid running into a bug when resolving nested references in reclass which we hit with the old structure
See https://github.com/kapicorp/reclass/pull/8 for a potential fix of the underlying reclass bug.

Restructure K8up image specification

---

component/monitoring.jsonnet
tests/golden/v1/backup-k8up/backup-k8up/30_monitoring.yaml
tests/golden/v2/backup-k8up/backup-k8up/30_monitoring.yaml

Some components base their alert routing on the existence of the `syn` label and the `syn_component` label can be useful during troubleshooting.

Add syn labels to alert rules

---

Makefile.vars.mk
component/main.jsonnet
component/monitoring.jsonnet
tests/golden/v2/backup-k8up/backup-k8up/00_namespace.yaml
tests/golden/v2/backup-k8up/backup-k8up/30_monitoring.yaml
tests/v2.yml

The component `prometheus` supports cluster-monitoring, where the namespace, PrometheusRules and monitors need a specific label.
This commit will add the required labels.
Signed-off-by: Nicolas Bigler <nicolas.bigler@vshn.ch>

Add monitoring labels to support component-prometheus

---

component/monitoring.jsonnet
docs/modules/ROOT/pages/references/parameters.adoc

Adds the possibility to exclude individual alert rules from class/defaults.yml by setting their value to `null`

Enable ignoring individual default alert rules

---

class/backup-k8up.yml
class/defaults.yml
docs/modules/ROOT/pages/references/parameters.adoc
postprocess/cleanup-job.jsonnet
tests/golden/defaults/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/cleanup-hook.yaml

We `parameters.backup_k8up.images.kubectl` and add a postprocessing filter which patches the cleanup job to use the image location specified in that image parameter.
changelog.

Make Helm chart cleanup job container image configurable

---

class/backup-k8up.yml
component/crds.jsonnet
tests/golden/defaults/backup-k8up/backup-k8up/02_k8up_crds.yaml

This prevents sync errors when the last-applied-configuration annotation becomes too big.
changelog.

Add ArgoCD sync server-side apply for CRDs

---

class/defaults.yml
tests/golden/defaults/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/deployment.yaml

`skipWithoutAnnotation` is a helm value, not an envvar
changelog.

Fix misconfigured helm value for `skipWithoutAnnotation`
